apiVersion: v1
kind: ConfigMap
metadata:
  name: yarp-config
data:
  yarp.json: |
    {
      "ReverseProxy": {
        "Routes": {
          "users-route": {
            "ClusterId": "users-cluster",
            "Match": {
              "Path": "users-api/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          },
          "auth-route": {
            "ClusterId": "auth-cluster",
            "Match": {
              "Path": "auth-api/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          },
          "forums-route": {
            "ClusterId": "forums-cluster",
            "Match": {
              "Path": "forums-api/{**catch-all}"
            },
            "Transforms": [
              {
                "PathPattern": "{**catch-all}"
              }
            ]
          }
        },
        "Clusters": {
          "users-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://user-service:5110"
              }
            }
          },
          "auth-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://auth-service:5330"
              }
            }
          },
          "forums-cluster": {
            "Destinations": {
              "destination1": {
                "Address": "http://forum-service:5220"
              }
            }
          }
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: 11112002/apigateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8000;
          volumeMounts:
            - name: yarp-config
              mountPath: /app/yarp.json
              subPath: yarp.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: yarp-config
          configMap:
            name: yarp-config
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
