# combined-manifest.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: 11112002/apigateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8000;
          volumeMounts:
            - name: yarp-config
              mountPath: yarp.json
              subPath: yarp.json
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: yarp-config
          configMap:
            name: yarp-config
---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
