version: '3.4'

services:
  apigateway:
    image: apigateway:latest
    networks:
        - backend
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

networks:
  backend:
    name: backend
    external: true
    driver: bridge
